tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "curl"
brew "git"
brew "mas"
brew "node-build"
brew "nodenv"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rbenv"
brew "ruby-build"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "appcleaner"
cask "discord"
cask "docker"
cast "fig"
cask "figma"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "obs"
cask "slack"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "vivaldi"
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "Logic Pro", id: 634148309
mas "MainStage", id: 634159523
mas "Motion", id: 434290957
mas "The Unarchiver", id: 425424353
mas "Tweetbot", id: 1384080005
